-- Migration: 010_seed_system_plants.sql (REESCRITA)
--
-- A versão anterior criava o usuário "sistema" e as 4 plantas de catálogo
-- com IDs FIXOS/PREVISÍVEIS ('00000000-0000-0000-0000-00000000000X') e um
-- hash de senha conhecido/zerado. Isso é uma falha de segurança: qualquer
-- pessoa que leia o código/migrations conhece esses IDs e o hash.
--
-- Esta migration não insere dados. O seed do usuário sistema e do catálogo
-- público (Manjericão, Salsinha, Hortelã, Alecrim) é feito em Rust, no boot
-- da aplicação, via Database::seed_system_catalog():
--   - usuário sistema com UUID v4 aleatório e senha aleatória (bcrypt)
--   - identificado pela flag users.is_system = 1 (não por ID fixo)
--   - plantas de catálogo com UUID v4 aleatório, created_by = id do sistema,
--     publica = 1
--   - idempotente: só insere se ainda não existir
--
-- Ver migration 013_add_is_system_flag.sql para a coluna users.is_system.
